config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :docs
  get 'welcome/index'

  resources :doc
  authenticated :user do
    root to: 'docs#index', as: 'authenticated_root'
  end

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.where(user_id: current_user).order('created_at DESC')
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = current_user.docs.build
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = current_user.docs.build(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_blank.html.haml
%h1 Your blank message here

app/views/docs/_doc.html.haml
%tr
  %td= doc.id
  %td= doc.title
  %td= doc.content
  %td.action
    = link_to(doc, class: 'btn btn-success', toogle: 'tooltip', title: t('tooltips.zoom')) do
      %i.icon-zoom-in
    = link_to(edit_doc_path(doc) , class: 'btn btn-info') do
      %i.icon-edit
    = link_to(doc, class: 'btn btn-danger', method: :delete) do
      %i.icon-trash

app/views/docs/_filters.html.haml
.table-header.row
  .col-lg-9
    TODO: Add filters here
  .col-lg-3
    = search_form_for @search, builder: SimpleForm::FormBuilder do |f|
      .input-group
        = f.input_field :title_or_content_cont, label: false, input_html: {class: 'form-control'}, placeholder: 'Quick search...'
        %span.input-group-btn
          = button_tag( class: 'btn') do
            %i.icon-search

app/views/docs/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title
  .panel-body
    = simple_form_for(@doc) do |f|
      = f.error_notification

      .form-inputs
        = f.input :title
        = f.input :content

      .form-actions
        = f.button :submit, class: 'btn btn-default'
        = link_to t('cancel'), docs_path, class: 'btn'

app/views/docs/_list.html.haml
.panel-heading
  %i.icon-table.icon-large
  = t('tt.index', resource_name: Doc.model_name.human)
  .panel-tools
    .btn-group
      %a.btn{href: docs_path, data: {toggle: 'toolbar-tooltip'}, title: 'Reload'}
        %i.icon-refresh
    .badge= @docs.total_entries
.panel-body.filters
  = render 'filters'
%table.table
  %thead
    %tr
      %th #
      %th= sort_link(@search, :title, t('activerecord.attributes.doc.title'))
      %th= sort_link(@search, :content, t('activerecord.attributes.doc.content'))
      %th.actions
        Actions
  %tbody
    = render @docs

app/views/docs/edit.html.haml
- content_for :form_title do
  = t('tt.edit', resource_name: Doc.model_name.human)
= render 'form'

app/views/docs/index.html.haml
- content_for :toolbar do
  = link_to new_doc_path, class: 'btn btn-default' do
    %i.icon-plus
    = t('action_button.new', resource_name: Doc.model_name.human)

.panel.panel-default.grid
  .panel-body
    -@docs.each do |doc|
      %h2= link_to doc.title, doc
      %p= time_ago_in_words(doc.created_at)
      %p= truncate(doc.content, length: 50)

app/views/docs/new.html.haml
- content_for :form_title do
  = t('tt.new', resource_name: Doc.model_name.human)
= render 'form'

app/views/docs/show.html.haml
- content_for :toolbar do
  = link_to edit_doc_path(@doc ), class: 'btn btn-default' do
    %i.icon-pencil
    = t('action_button.edit')
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = t('tt.show', resource_name: Doc.model_name.human)
  .panel-body
    = show_for @doc do |s|
      = s.attribute :title
      = s.attribute :content
    = link_to 'All Docs', docs_path
    = link_to 'Fix Doc', edit_doc_path(@doc)
    = link_to 'Trash It', doc_path(@doc), method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Run Stefano Run &infin;
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        = link_to 'Run Stefano Run', root_path

        %nav
          - if user_signed_in?
            = link_to 'Create Memento', new_doc_path
            = link_to 'Logout', destroy_user_session_path, method: :delete
          - else
            = link_to 'Sign in', new_user_session_path

    - flash.each do |type, msg|
      %div{:class => "alert alert-#{type == :notice ? "success" : type} fadeout", "data-dismiss" => "alert"}
        %button.close &times;
        = msg if msg.is_a?(String)

    = yield

app/views/layouts/hq/application.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    = csrf_meta_tags

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'hq/application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css',
                          media: 'all', 'data-turbolinks-track' => true

    / Javascripts
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                              'hq/application', 'data-turbolinks-track' => true
    = yield :head

  %body.main

    / Navbar
    = render partial: 'layouts/hq/partials/navbar'

    #wrapper

      / Sidebar
      %section#sidebar
        = render partial: 'layouts/hq/partials/dock'

      / Tools
      %section#tools
        = render partial: 'layouts/hq/partials/breadcrumb'
        = render partial: 'layouts/hq/partials/toolbar'

      / Content
      #content
        = render partial: 'layouts/partials/messages'
        = yield

    / Footer
    = render partial: 'layouts/hq/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/hq/partials/_breadcrumb.haml
%ul#breadcrumb.breadcrumb
  = render_breadcrumbs :separator => ' / '

app/views/layouts/hq/partials/_dock.haml
%i#toggle.icon-align-justify.icon-large

%ul#dock
  %li.launcher
    %i.icon-dashboard
    =link_to  t('dock.dashboard'), hq_dashboard_index_path
  %li.launcher
    %i.icon-file-text-alt
    =link_to 'Forms', '/hq/dashboard/form.html'
  %li.launcher
    %i.icon-table
    =link_to 'Tables', '/hq/dashboard/tables.html'
  %li.launcher.dropdown.hover
    %i.icon-flag
    %a{href: '#'} Reports
    %ul.dropdown-menu
      %li.dropdown-header Launcher description
      %li
        %a{:href => '#'} Action
      %li
        %a{:href => '#'} Another action
      %li
        %a{:href => '#'} Something else here
  %li.launcher
    %i.icon-bookmark
    %a{href: '#'} Bookmarks
  %li.launcher
    %i.icon-cloud
    %a{href: '#'} Backup
  %li.launcher
    %i.icon-bug
    %a{href: '#'} Feedback

#beaker{data: {toggle: 'tooltip'}, title: 'Made by lab2023'}

app/views/layouts/hq/partials/_footer.haml
= yield :foot

app/views/layouts/hq/partials/_navbar.haml
#navbar.navbar.navbar-default
  %a.navbar-brand{:href => hq_root_path}
    %i.icon-beer
    Hierapolis
  %ul.nav.navbar-nav.pull-right
    %li.dropdown
      %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
        %i.icon-envelope
        Messages
        %span.badge 5
        %b.caret
      %ul.dropdown-menu
        %li
          %a{:href => '#'} New message
        %li
          %a{:href => '#'} Inbox
        %li
          %a{:href => '#'} Out box
        %li
          %a{:href => '#'} Trash
    %li
      %a{href: '#'}
        %i.icon-cog
        = t('navbar.settings')
    %li.dropdown.user
      %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
        %i.icon-user
        %strong
          = current_admin.email
        =image_tag 'http://lorempixel.com/output/fashion-q-c-20-20-4.jpg', width: '20px', height: '20px', class: 'img-rounded'
        %b.caret
      %ul.dropdown-menu
        %li
          =link_to t('navbar.edit_profile'), edit_hq_admin_profile_path
        %li.divider
        %li
          =link_to t('navbar.signout'), destroy_admin_session_path, method: :delete

app/views/layouts/hq/partials/_toolbar.haml
#toolbar
  .btn-group
    = yield :toolbar

app/views/layouts/login.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'hq/application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css',
                          media: 'all', 'data-turbolinks-track' => true
    = yield :head

  %body.login

    .wrapper
      = render partial: 'layouts/partials/messages'
      = yield

    / Footer
    = render partial: 'layouts/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'application', 'data-turbolinks-track' => true

app/views/layouts/partials/_messages.haml
- flash.each do |key, value|
  - if key.to_s == "notice"
    - key = "success"
  - if key.to_s == "alert"
    - key = "danger"
  %div{:class => "alert alert-dismissable alert-#{key}"}
    - if key.to_s == "danger" || key.to_s == "warning"
      %i.fa.fa-exclamation-triangle.fs-25
      %strong
        = t('messages.sorry')
        \!
    - else
      %i.fa.fa-smile-o.fs-25{:style => "padding: 0px 5px;"}
    = value

app/views/layouts/partials/_trackers.haml
:javascript
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml